# SITE CONFIGURATION
baseurl: "/"
url: "https://www.netz39.de"

# BOARD MEMBERS
board:
  chair:
    name: "Lena Prieß"
#    wiki: ""
  deputy:
    name: "Felix Kranz"
#    wiki: ""

# THEME-SPECIFIC CONFIGURATION
title: Netz39 e.V.                                      # site's title
description: "Magdeburger Hackerspace"                  # used by search engines
avatar: https://cdn.netz39.de/img/logo/netz39-logo-final.svg           # Empty for no avatar in navbar
favicon: https://cdn.netz39.de/img/logo/netz39-logo-icon.svg           # Icon displayed in the tab

# Header and footer text
header_text: Netz39 e.V. — ein Hackerspace für Magdeburg und Umgebung # Change Blog header text
header_feature_image: https://cdn.netz39.de/img/header/bg-featured-1.jpg
header_feature_image_responsive: true
footer_text: >
  Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>

# Show share_buttons
share_buttons: false

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: https://cdn.netz39.de/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: default                                        # Enable mermaid-js for diagrams, use theme: base, forest, dark, default, neutral
google_analytics:                                       # Measurement ID, e.g. "G-00000"
cookie_consent: false                                   # To respect the usage of cookies
color_theme: auto                                       # auto, dark or light

# Comments options
comments:
  disqus_shortname:                                     # Your discus shortname for comments
  cusdis_app_id:                                        # Your cusdis data-app-id
  utterances:                                           # Enable by filling below information. For more info, go to https://utteranc.es
    repo:                                               # your public comments repository (e.g. owner/repo)
    issue-term:                                         # Issue term (e.g. "comment" consider issues with this word in the title as comments)

# PAGINATION
paginate: 8
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name
  events:
    output: true
    permalink: /events/:path
    title: Events

# BUILD SETTINGS
github:
  repository_url: https://github.com/netz39/www.netz39.de
sass:
  style: compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".jekyll-metadata", ".idea", "vendor/*", "assets/node_modules/*", "README.md", "docker-compose.yml", "Gemfile", "type-on-strap.gemspec", "tools"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
